# Generated by Django 5.1.2 on 2024-10-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktuguideapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_branch', to='ktuguideapp.branch')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ktuguideapp.semester')),
            ],
        ),
    ]
