# Generated by Django 5.1.2 on 2024-11-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktuguideapp', '0003_semester_sem_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
    ]
