# Generated by Django 5.1.2 on 2024-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktuguideapp', '0004_remove_newsletter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktuupdates',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
